import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import Search from "@/components/Search";

const roboto = Roboto({
  weight: ["400"],
  variable: "--font-roboto",
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const montserrat = Montserrat({
  weight: ["300", "400"],
  variable: "--font-montserrat",
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <div className="md:flex gap-x-4 bg-[--primary-color] p-4">
          <Sidebar />
          <div className="flex-1 min-h-screen rounded-lg">
            <Search />
            <div className="my-4">{children}</div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
